server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  # consul注册中心地址
  cloud:
    consul:
      host: localhost
#      host: 192.168.136.128
      port: 8500
      discovery:
        #hostname: localhost
        #service-name: ${spring.application.name}
        heartbeat:
          enabled: true
