server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 # 配置nacos地址
        server-addr: 192.168.136.128 # nginx访问nacos集群
management:
  endpoints:
    web:
      exposure:
        include: "*"