server:
  port: 80

eureka:
  client:
    register-with-eureka: false # 不注册进Eureka服务注册
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# 设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  # 建立连接所需要的时间，适用于网络状况正常的情况下，两端连接所用的时间（单位ms）
  ConnectTimeout: 5000
  # 建立连接后从服务器读取到可用资源所用的时间（单位ms）
  ReadTimeout: 5000

# 设置feign日志对象及级别
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug